In [2]:
import random 
import numpy as np
import pandas as pd

with open("names.txt",encoding="utf-8") as file:
    content = file.read()

names_list = content.split()
names = random.choices(names_list,k=50)

with open("names.txt",encoding="utf-8") as file:
    content = file.read()
    
scores = np.random.randint(50,101,size=(50,5))
student_df = pd.DataFrame(scores,
             columns=['國文','英文','數學','地理','歷史'],
             index=names)
student_df

      國文   英文  數學  地理  歷史
張慧君   79   59  92  69  54
鄧亭聿   91   62  80  56  64
楊建安   98   72  96  57  71
林佳人   56   58  65  85  59
臧怡君   69   61  66  70  95
鍾俞禎   51   50  84  95  78
鄭憲定   60   74  96  78  63
杜明延   52   78  87  58  76
羅佩樺   91   74  75  58  64
黃詩妃   75   73  78  96  99
黃奎紹   71   88  65  54  78
馬彥文   80   79  67  77  51
蔡偉成   53   84  53  77  94
王雅慧   72   86  70  77  72
鄭佳玲   74   99  87  50  97
黃麗美   58   71  91  62  95
林建勳   97   68  57  87  57
王良斌   70   81  84  88  75
鄧哲榮   82   59  83  69  68
胡芳瑜   98   86  62  89  84
鍾俞禎   63   96  82  88  89
李政白   54   90  81  62  63
余宗儒   82   80  99  79  99
蔡欣汝   76   57  90  77  52
陳怡珊   50   77  96  94  97
李湘婷   55   56  86  50  93
陳建豪   96   75  59  84  95
謝南慧  100   56  69  62  60
黃佩玲   57   86  75  88  77
劉林中   90   97  96  68  91
王志謙   65  100  50  58  79
劉耿琦   91   57  51  61  96
陳逸華   97   68  72  96  73
郎慧萍   74   86  63  81  61
黃偉剛   58   74  91  72  94
蕭怡伶   52   55  76  93  61
林志成   58   70  56  51  73
林佳人   57   75  60  97  81
李立偉   91   78  95  63  77
吳麗卿   50   61  70  93  78
王士銘   53  100  86  61  58
張莉雯   82   71  71  72  92
李雅怡   80   76  98  66  69
李蓉瑞   50   68  78  63  96
張彥博   60   78  71  53  62
吳麗卿   76   52  91  81  99
李彥伸   99   58  80  78  84
張慧君   79   74  91  75  89
陳彥治   77   96  76  90  69
游一鈺   59   77  65  52  99

In [3]:
student_df['國文']
student_df[['國文','英文']]

      國文   英文
張慧君   79   59
鄧亭聿   91   62
楊建安   98   72
林佳人   56   58
臧怡君   69   61
鍾俞禎   51   50
鄭憲定   60   74
杜明延   52   78
羅佩樺   91   74
黃詩妃   75   73
黃奎紹   71   88
馬彥文   80   79
蔡偉成   53   84
王雅慧   72   86
鄭佳玲   74   99
黃麗美   58   71
林建勳   97   68
王良斌   70   81
鄧哲榮   82   59
胡芳瑜   98   86
鍾俞禎   63   96
李政白   54   90
余宗儒   82   80
蔡欣汝   76   57
陳怡珊   50   77
李湘婷   55   56
陳建豪   96   75
謝南慧  100   56
黃佩玲   57   86
劉林中   90   97
王志謙   65  100
劉耿琦   91   57
陳逸華   97   68
郎慧萍   74   86
黃偉剛   58   74
蕭怡伶   52   55
林志成   58   70
林佳人   57   75
李立偉   91   78
吳麗卿   50   61
王士銘   53  100
張莉雯   82   71
李雅怡   80   76
李蓉瑞   50   68
張彥博   60   78
吳麗卿   76   52
李彥伸   99   58
張慧君   79   74
陳彥治   77   96
游一鈺   59   77

In [6]:
student_df.loc['張慧君']
student_df.loc[['陳彥治','李彥伸']]

     國文  英文  數學  地理  歷史
陳彥治  77  96  76  90  69
李彥伸  99  58  80  78  84

In [7]:
student_df.iloc[0]
student_df.iloc[[0,49]]
student_df.iloc[:5]
student_df.iloc[-5:]

     國文  英文  數學  地理  歷史
吳麗卿  76  52  91  81  99
李彥伸  99  58  80  78  84
張慧君  79  74  91  75  89
陳彥治  77  96  76  90  69
游一鈺  59  77  65  52  99

In [8]:
student_df.iloc[-5:,:3]

     國文  英文  數學
吳麗卿  76  52  91
李彥伸  99  58  80
張慧君  79  74  91
陳彥治  77  96  76
游一鈺  59  77  65

In [9]:
#值的選取
student_df[student_df['地理'] < 60]

     國文   英文  數學  地理  歷史
鄧亭聿  91   62  80  56  64
楊建安  98   72  96  57  71
杜明延  52   78  87  58  76
羅佩樺  91   74  75  58  64
黃奎紹  71   88  65  54  78
鄭佳玲  74   99  87  50  97
李湘婷  55   56  86  50  93
王志謙  65  100  50  58  79
林志成  58   70  56  51  73
張彥博  60   78  71  53  62
游一鈺  59   77  65  52  99

In [10]:
student_df[student_df['國文'] < 60]

     國文   英文  數學  地理  歷史
林佳人  56   58  65  85  59
鍾俞禎  51   50  84  95  78
杜明延  52   78  87  58  76
蔡偉成  53   84  53  77  94
黃麗美  58   71  91  62  95
李政白  54   90  81  62  63
陳怡珊  50   77  96  94  97
李湘婷  55   56  86  50  93
黃佩玲  57   86  75  88  77
黃偉剛  58   74  91  72  94
蕭怡伶  52   55  76  93  61
林志成  58   70  56  51  73
林佳人  57   75  60  97  81
吳麗卿  50   61  70  93  78
王士銘  53  100  86  61  58
李蓉瑞  50   68  78  63  96
游一鈺  59   77  65  52  99

In [11]:
#地理和國文同時不及格的
student_df[(student_df['地理']<60)&(student_df['國文']<60)]

     國文  英文  數學  地理  歷史
杜明延  52  78  87  58  76
李湘婷  55  56  86  50  93
林志成  58  70  56  51  73
游一鈺  59  77  65  52  99

In [12]:
#地理和國文同時不及格的
student_df[(student_df['地理']<60)| (student_df['國文']<60)]

     國文   英文  數學  地理  歷史
鄧亭聿  91   62  80  56  64
楊建安  98   72  96  57  71
林佳人  56   58  65  85  59
鍾俞禎  51   50  84  95  78
杜明延  52   78  87  58  76
羅佩樺  91   74  75  58  64
黃奎紹  71   88  65  54  78
蔡偉成  53   84  53  77  94
鄭佳玲  74   99  87  50  97
黃麗美  58   71  91  62  95
李政白  54   90  81  62  63
陳怡珊  50   77  96  94  97
李湘婷  55   56  86  50  93
黃佩玲  57   86  75  88  77
王志謙  65  100  50  58  79
黃偉剛  58   74  91  72  94
蕭怡伶  52   55  76  93  61
林志成  58   70  56  51  73
林佳人  57   75  60  97  81
吳麗卿  50   61  70  93  78
王士銘  53  100  86  61  58
李蓉瑞  50   68  78  63  96
張彥博  60   78  71  53  62
游一鈺  59   77  65  52  99